### ISSUE TITLE
Java8 is unavailable due to licensing changes

### ISSUE THREAD

**Issue by Marvino-il-Marziano** [researchspace/researchspace#10]
The installation guide links to an article for installing Java8, http://www.lonecpluspluscoder.com/2017/10/08/installing-other-versions-of-the-java-jdk-via-homebrew/ but atop it says "Update 2019-05-07: The java8 cask is affected by recent licensing changes by Oracle. There’s a discussion over on github about this. I’m leaving the post up partially for historic context, but the java8 cask is no longer available, at least at the time of writing.".

It must be important to have Java8 as your install guide mentions "by default Java9 is installed, here is how to get Java8" which is now not possible anymore. And indeed I get a score of errors when trying to install on Macos 10.14 Mojave; specifically at the step ./build.sh compile --- "java.lang.AssertionError: assertion failed: not a type: symbol".

**Comment by aindlq** [comment]
There are non Oracle builds available through homebrew, for example https://adoptopenjdk.net/, see updated installation instruction - https://github.com/researchspace/researchspace#prerequisites-installation-on-macos-mojave

Also now you don't need to build it from sources and can use docker images, see https://github.com/researchspace/researchspace#setup-with-docker
