### ISSUE TITLE
No getting started documentation

### ISSUE THREAD

**Issue by adamretter** [researchspace/researchspace#104]
Hi there,

I have got ResearchSpace running locally using the Docker Compose basic setup. I have also logged in successfully via http://localhost:10214/resource/rsp:Start.

Unfortunately I now have no idea where to begin with setting up and configuring the system. I have only found very minimal developer documentation which isn't helpful from a "Getting Started" perspective. I have looked on researchspace.org, I have also looked for a GitHub Wiki, a docs folder, and the in-browser docs within ResearchSpace, but found nothing useful.

We have a large amount of RDF data that we would like to load into ResearchSpace and experiment with. We have no rigid Ontology as we reuse many parts of other ontologies such as Dublin Core, PREMIS, and RDA.

I am technically proficient, but setting up ResearchSpace with our data at the moment appears non-trivial! Can someone point me towards a Setup and Getting Started guide or any other comprehensive documentation?

Thanks

**Comment by PaulWang1905** [comment]
There are some papers in which you can see how to link DC to CIDOC CRM I think. You can also upload data via sparql or a web page.

**Comment by lklic** [comment]
Please see here:
https://documentation.researchspace.org/resource/rsp:Start
