### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jpadfield** [researchspace/researchspace#11]
Hi, 

I am trying to build ResearchSpace on a Ubuntu 16.04 and have reached the stage of running:
 ./build.sh compile

The process runs but two packages that it tries to install are returning 404:

[error] error An unexpected error occurred: "https://codeload.github.com/aindlq/html-to-react-1/tar.gz/f33c348a229d0b2a46dc837d6104d91f0bbe30d2: Request failed \"404 Not Found\"".

called in: https://github.com/researchspace/researchspace/blob/master/metaphactory/web/package.json

[error] error An unexpected error occurred: "https://codeload.github.com/aindlq/html-to-react-1/tar.gz/f33c348a229d0b2a46dc837d6104d91f0bbe30d2: Request failed \"404 Not Found\"".

called in:
https://github.com/researchspace/researchspace/blob/master/researchspace/web/package.json

There are obviously a few alternative versions for both, can you please recommend which alternatives these might be replaced with?

Thanks

**Comment by jpadfield** [comment]
Replacing with the following version :

* "openseadragon": "2.4.1",
* "html-to-react": "1.2.4",
and then also 
* "react-scrollchor": "6.0.0",

Allowed everything to build - just checking if it then works though :-)

**Comment by jpadfield** [comment]
So near yet so far :-(

Everything builds and the system works in the browser at http://localhost:10214 

But then it seems to hang on a grey screen with the faint message "Please wait ...."

I have waited a while now but it seems like it is stuck and there have not been any errors shown in the terminal messages.

**Comment by jpadfield** [comment]
The "resource/rsp:Search" page is throwing up a number of JavaScript errors related to:
"Objects are not valid as a React child (found: [object Promise])."

So I guess the alternative "html-to-react" and possibly "react-scrollchor" are not going to work at the moment.

So it would be great to hear what should be used instead?

Thanks

**Comment by aindlq** [comment]
Should be fixed in the latest version. If you are not intending to modify the source code you can use docker images to setup ResearchSpace - https://github.com/researchspace/researchspace#setup-with-docker

We are currently working no demo applications for various Cultural Heritage use-cases, stay tuned.
