### ISSUE TITLE
Image Upload, Failed to submit the form

### ISSUE THREAD

**Issue by MacGros** [researchspace/researchspace#113]
Morning,

Successfully loaded the LDP container, a small test run ttl as a named graph, enjoyed the [documentation](http://localhost:10214/resource/Help:Start) (and found two minor errors in the SPARQL query examples, GRPAH instead of GRAPH, might try to solve it by myself).

Tried to load this image via the load image form (http://localhost:10214/resource/:ProjectImages) :
![3000](https://user-images.githubusercontent.com/19284045/94235276-9489bf80-ff0b-11ea-9c68-cdaccd084809.jpg)

Popup "Failed to submit the form" and the corresponding log is :
`2020-09-25 06:44:22 ERROR [qtp2035070981-13] (FileStorageEndpoint.java:278) - Failed to move file: file/296816071770846333_3000.jpg`

Using the [File Upload](http://localhost:10214/resource/Admin:FileUpload) interface
+ Target Storage : runtime / Target Folder : assets --> Ok (but not the good folder to work with I assume)
+ Target Storage : images / Target Folder : file --> `2020-09-25 07:03:08 ERROR [qtp2035070981-16] (FileStorageEndpoint.java:93) - java.nio.file.AccessDeniedException: /images/assets`

Bests,
Antoine

**Comment by aindlq** [comment]
Again file permissions :(, can you run `sudo sh ./fix-folder-permissions.sh` script one more time, it should fix the problem.

jfyi, File Upload in admin area should be only used when you just need file to use it in the template page, for example institution logo, or some other image. When you upload file this way it doesn't create and RDF data for it. On the other hand Project Images upload create associated RDF data and image can be refereed by other resources, viewed in IIIF viewer, etc.

**Comment by MacGros** [comment]
Strange enough, it seems that I had to run it a second time (maybe I'm dishonest, I recreated a docker in the late night).
Again, thanks to you @aindlq 

Thanks for the jyfi. Enlightning 

Good evening
Antoine
