### ISSUE TITLE
Template could not be found ( Admin / Ontologies )

### ISSUE THREAD

**Issue by linkedDataDeveloper** [researchspace/researchspace#117]
When exploring a newly added ontology ( `Home / Administration / Ontologies / <myOntology>` ) clicking on any class: 

`Template:rdfs:Class:120:879: The partial '/http://www.researchspace.org/resource/LinksToOtherDatabases.hbs' at 'Storage object "data/templates/http%3A%2F%2Fwww.researchspace.org%2Fresource%2FLinksToOtherDatabases.html"' could not be found `

Running Docker-Compose-Basic using a non CIDOC CRM ontology without any KPs configured.

**Comment by aindlq** [comment]
Are you sure that you are using the latest version, can you try to do `docker pull researchspace-ci:latest` and then `docker-compose up -d` again? see my message in gitter - https://gitter.im/researchspace/community?at=5f7394cf4002c640b5f5b203

**Comment by linkedDataDeveloper** [comment]
Success!

note:
```
docker pull researchspace/platform-ci:latest
docker-compose up -d
```
