### ISSUE TITLE
Graph statistics (limit >1m)

### ISSUE THREAD

**Issue by linkedDataDeveloper** [researchspace/researchspace#119]
When navigating to statistics under  `Home > Administration > Data Import and Export > Named Graph` 

returns 

`Statics are only available for named graph with less than 1.000.000 statements. However, the absolute number of statements in the graph seems to be larger`

Can this limit be increased, or does it crash beyond 1m statements?

**Comment by aindlq** [comment]
You can increase the limit, go to http://localhost:10214/resource/Admin:NamedGraphs?action=edit , you need to change LIMIT in sparql query https://github.com/researchspace/researchspace/blob/master/src/main/resources/org/researchspace/apps/system/data/templates/http%253A%252F%252Fwww.researchspace.org%252Fresource%252Fadmin%252FNamedGraphs.html#L86 and limit in the if statement - https://github.com/researchspace/researchspace/blob/master/src/main/resources/org/researchspace/apps/system/data/templates/http%253A%252F%252Fwww.researchspace.org%252Fresource%252Fadmin%252FNamedGraphs.html#L93

**Comment by linkedDataDeveloper** [comment]
Solved
