### ISSUE TITLE
No search results for new dataset

### ISSUE THREAD

**Issue by linkedDataDeveloper** [researchspace/researchspace#121]
Under  `Administration > Data Import and Export > Named Graph: <myData>` I can see all my newly added data (not CIDOC), click through different resources, and navigate through the resource as a knowledge graph.

However, when I navigate to search/structured search under thinking frames, search does not yield results containing resources from the new data set, therefore I cannot add resources to the clipboard, and cannot build knowledge maps.

What is the process for setting up search? Does this require knowledge patterns? Is there a guide to setting up search, or developing new knowledge patterns?

Running docker-compose-basic.

**Comment by aindlq** [comment]
By default we make assumption that we are dealing with data that is in CIDOC-CRM and generate search configuration form Knowledge Patterns, here is search template https://github.com/researchspace/researchspace/blob/master/src/main/resources/org/researchspace/apps/default/data/templates/http%253A%252F%252Fwww.researchspace.org%252Fresource%252FSearchContent.html locally it is accessible through http://localhost:10214/resource/rsp:SearchContent?action=edit .

> What is the process for setting up search? Does this require knowledge patterns?

You can generate search config from knowledge patterns as we do by default or define the whole config inline in the template.

> Is there a guide to setting up search, or developing new knowledge patterns?

Search documentation - http://localhost:10214/resource/resource/Help:SemanticSearch
