### ISSUE TITLE
Simple search does not yield results (following Metaphacts tutorial)

### ISSUE THREAD

**Issue by linkedDataDeveloper** [researchspace/researchspace#124]
I'm following the [Metaphacts Getting Started Tutorial](https://help.metaphacts.com/resource/Help:Start?tab=Tutorial). I have loaded the sample RDF. As per the tutorial, I can explore the data by clicking on a resource (with the exception that RS is not rendering thumbnails).  One of the initial steps is to use simple search to locate "Bob". When I search for "Bob", I get no results. This does not meet the behaviour described in the tutorial. Does search require some configuration? Should there be extra steps in the tutorial? Same behaviour is exhibited when building from source or from researchspace-docker-compose.

**Comment by aindlq** [comment]
My guess is most likely something is wrong with your data or your query template for search. 

In essence `semantic-simple-search` just parametrize supplied query template with user input and sends it to the platform's sparql endpoint, you can always open browser network inspector and check what is actually send, you can then copy the query and debug it in the sparql editor:
![2020-10-16-130938_2560x1440_scrot](https://user-images.githubusercontent.com/2255044/96283447-e5f60d80-0fe4-11eb-88ab-903ef713fe19.png)


Next time please attach the template snippet that is in question. 

Also as @doldman commented here -  https://github.com/researchspace/researchspace/issues/112#issuecomment-705747423 , "There is now no connection with Metaphacts who were a technical supplier". So it is hard for us to comment on their tutorial, there most likely can be discrepancy with ResearchSpace configuration. So always double check the config with current ResearchSpace documentation.

**Comment by linkedDataDeveloper** [comment]
Thank you for the feedback. I was just about to clarify. I am able to generate the expected behaviour from a new page with the simple-search template provided by the tutorial. That works as expected. 

My question is in regards to how search has been implemented in ResearchSpace, specifically here: `http://localhost:10214/resource/:ThinkingFrames?view=simple-search`. To simplify my testing of RS, I am using [the tutorial data](https://help.metaphacts.com/metaphacts/samples/sample.ttl), which is just some very simple RDF. When I create a new template in RS:
`<semantic-simple-search
    query='
      SELECT ?resource ?label WHERE {
       FILTER REGEX(?label, ?__token__, "i")
       ?resource rdfs:label ?label
      } LIMIT 10'
    template='<span style="color: blue;" title="{{resource.value}}">{{label.value}}</span>'
    placeholder='Search for something e.g. "Bob"'>
</semantic-simple-search>`

The search works: I can find the data I recently uploaded. 

When I search using the ResearchSpace search page, I do not get any results for the same dataset. I would like to know if there is additional documentation that explains more about specific implementations in ResearchSpace.

Thank you for your help.

**Comment by aindlq** [comment]
I think your question is related to the one you asked in the other issue - https://github.com/researchspace/researchspace/issues/121#issuecomment-705811868 .

Default search template assumes that we are dealing with resources that are typed with some class from CIDOC-CRM, and that we are using blazegraph:

```
<semantic-search-query-keyword 
        domain='<http://www.cidoc-crm.org/cidoc-crm/E1_CRM_Entity>'
        query='
          SELECT ?subject WHERE { 
             ?subject a ?type .
             ?type rdfs:subClassOf* crm:E1_CRM_Entity .
             ?subject rdfs:label ?label .
             SERVICE <http://www.bigdata.com/rdf/search#search> {
               ?label bds:search ?__token__ ;
                        bds:minRelevance "0.3" ;
                        bds:matchAllTerms "true"  .
             }
          }
        '
```

you can just change that base query.
