### ISSUE TITLE
Structured Search for Geospatial project

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#131]
It seems that tweaking the structured search component is the best solution for our project. 
for instance, using the semantic map not only as of the result holder but also for add facets in the main query. 

Can this integration be feasible?

**Comment by aindlq** [comment]
It is already possible to some extent, you can select an area on a map and then use the selection in the query. Have a look at https://github.com/researchspace/researchspace/blob/master/src/main/web/components/search/query-builder/MapSelectionOverlay.tsx and https://github.com/researchspace/researchspace/blob/master/src/main/web/components/search/query-builder/OLMapSelection.tsx .

See attached PDF: 
[RKB-GeoSearch-301020-0851-300.pdf](https://github.com/researchspace/researchspace/files/5464010/RKB-GeoSearch-301020-0851-300.pdf)

**Comment by gspinaci** [comment]
Terrific! I'll start from here. thank you very much

**Comment by lklic** [comment]
closed this question, will open a new issue to document dev progress
