### ISSUE TITLE
semantic-map -- allow user to change basemap tiles or mapping provider

### ISSUE THREAD

**Issue by lklic** [researchspace/researchspace#136]
allow public users to modify the basemap, based on options configured at the component level

**Comment by aindlq** [comment]
@lklic do you have a requirement to show georeferenced historical maps? :).   

layer on/off + opacity, see https://viglino.github.io/ol-ext/examples/control/map.switcher.html . with IIIF layers for geo-referenced historical maps - https://openlayers.org/en/latest/examples/iiif.html. So we only need to think how we capture georeference data in RDF.

btw, we are already using ol-ext.

**Comment by gspinaci** [comment]
link to #162
