### ISSUE TITLE
WikidataSail controls should be based on Service Descriptor

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#171]
The code here checks that the query contains the property "hasWikidataSearchToken". An exception is thrown if the query doesn't provide the mandatory property.

https://github.com/researchspace/researchspace/blob/60233ec3181ff76c7dabb7a03a4e06b592db2166/src/main/java/org/researchspace/sail/rest/wikidata/WikidataSailConnection.java#L68-L76

The query and the service descriptor are allowed to have different URIs. Because of this configuration, different URIs for the same property may result in a SailException. 

We should have these URIs dynamically injected through the service descriptor and not harcoded in the code.

https://github.com/researchspace/researchspace/blob/60233ec3181ff76c7dabb7a03a4e06b592db2166/src/main/java/org/researchspace/sail/rest/wikidata/WikidataSailConnection.java#L54-L58

**Comment by lklic** [comment]
closing this issue as this has been fixed with PR #170
