### ISSUE TITLE
Error when uploading zipped app 

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#172]
In development mode, when uploading a zipped application I get the following issue
<img width="878" alt="image" src="https://user-images.githubusercontent.com/8267319/106125062-02652280-615c-11eb-9ab6-dffdfe6d1c10.png">

When I manually create the folder `runtime-data/apps` and I try again to upload an app, the problem doesn't show up.

**Comment by lklic** [comment]
I think this is expected behavior in dev mode. Feel free to reopen if this is something that needs to be addressed.
