### ISSUE TITLE
Additional data column in field visualization component

### ISSUE THREAD

**Issue by lklic** [researchspace/researchspace#18]
In our E22 template, we are loading up field definitions dynamically based on the domain and range using the mp-field-visualization component. For each field we would like to retrieve a specific URI that identifies the source of this data. We would prefer to do this by attaching a provenance note to each Named Graph

For example:
![image](https://user-images.githubusercontent.com/6654854/68588155-16eec980-0489-11ea-94fd-184e15617456.png)

In this screenshot that source column is hard coded just to show how it can look

To simplify the scenario lets say this is our field definition for an object "title" (in reality each field will be retrieving the source in different ways, here I am binding a value to ?source just to simplify):

```
SELECT $value ?label ?source
WHERE {
BIND ("I Tatti" as ?source) .
$subject a <http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object>.
$subject <http://www.cidoc-crm.org/cidoc-crm/P48_has_preferred_identifier> ?value
}
```

Now I would like to retrieve the value of ?source and place it into a separate column of the template.

The value of each field is currently retrieved by the template:
[FieldValueVisualization](https://github.com/researchspace/researchspace/blob/e0e51b0f8d56b7272cfb3f6574b3df67aa40dfcd/researchspace/app/data/templates/http%253A%252F%252Fwww.researchspace.org%252Fresource%252FFieldValueVisualization.html)

While I can create a new template and retrieve the named graph for that specific entity ie.
```
<div>
<semantic-query query='SELECT DISTINCT ?source WHERE {
GRAPH ?source
        { ?s ?p {{value.value}}  
          }
           }
>
</semantic-query>
</div>
```
Every time this field URI or value occurs in a named Graph it will return the URI of every named graph (I.e. resulting in multiple "source" nodes)

Unless I am missing some kind of a workaround, I see two possible solutions for dealing with this issue:

1. Allow us to retrieve additional values from the select query in the field definition (other than `?value`)

or

2. Create a new field within a field definition that allows you to write a new query to retrieve the source of the data.

Thoughts?

**Comment by aindlq** [comment]
What you want is already supported by `mp-field-visualization`, raw binding from `selectPattern` result  is available under `binding` variable. So if you add `test` binding to you field select pattern you can then access it as `value.binding.test.value` in your template. 

In general, you can use handlebars [log](http://handlebarsjs.com/builtin_helpers.html#log) function to check what is available in the current template scope, just add `{{log this}}` somewhere in your template.

**Comment by aindlq** [comment]
Also jfyi if you are using forms you can also access these additional bindings in `semantic-form-select-input` `template` property, that can be helpful if you want to add more information to select options for better disambiguation.

**Comment by lklic** [comment]
Thank you so much Artem, this is exactly what I needed!

It's working exactly as you described...
