### ISSUE TITLE
SSO login/logout button

### ISSUE THREAD

**Issue by linkedDataDeveloper** [researchspace/researchspace#197]
Optimize SSO feature by adding:
 * Link to OIDC login/logout screen from RS main header.
 * Make link dynamic (environmental variable?) so instances of researchspace in different environments (dev, stage, prod, etc.), can point to their respective keycloak instances (e.g dev vs prod)

**Comment by lklic** [comment]
Good point! I tested adding anonymous login with Keycloak as SSO provider and I was able to access the system as guest, but login/logout did not redirect me properly. 

I would also add a link to Keycloak account management page so users can change their password and update account info:

```<server-root>/auth/realms/{realm-name}/account```

**Comment by linkedDataDeveloper** [comment]
What settings did you change in Keycloak to allow the anonymous user to pass through without credentials?

**Comment by linkedDataDeveloper** [comment]
Replying to my own question for documentation sake. environment.prop needed the following additions to circumvent sso with an anonymous login:
```
shiroAuthenticationFilter=anon,authc
enableLocalUsers=true
```

**Comment by linkedDataDeveloper** [comment]
Is there any movement on adding this link? @aindlq

**Comment by linkedDataDeveloper** [comment]
Discussed today with @aindlq. He has a busy few weeks ahead of him. We will address this issue again in October at our next meeting. Goal is to have this complete by end of this year.

**Comment by lklic** [comment]
this is now working, as far as I know
