### ISSUE TITLE
URL Config for Proxy Setups

### ISSUE THREAD

**Issue by jpadfield** [researchspace/researchspace#209]
Hi,

I was experimenting with setting up a proxy redirect to the default port:

https://namespace.url/rs -> http://localhost:10214

The redirect works but the first step for login is redirecting in a different way so 

https://namespace.url/rs redirects to https://namespace.url/login

So this obviously fails is there any way to ensure that a proxy redirect can work?

Thanks

**Comment by jpadfield** [comment]
There seems like there may also be an issue related to some links to http://localhost:3000 for assets

Thanks

**Comment by aindlq** [comment]
just a summary of the chat with @jpadfield: Joe was trying to use development setup one the server, one shouldn't do that because dev setup is a local development environment to work on the source code. For any kind of deployments one should use docker or zip distribution.
