### ISSUE TITLE
Check if a REST response is transposed

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#247]
There is at least one case where the response body of an API endpoint is structured as follows:
```
{
   "image_ids": [
        2028654,
        1805479,
        1147864
   ],
   "scores": [
        33.0,
        26.0,
        26.0
   ]
}
```

The idea is to programmatically check if the body is structured in this way, and update accordingly to this structure
```
{
   [
      {
         "image_ids": 2028654,
         "scores": 33.0
      },
      {
         "image_ids": 1805479,
         "scores": 26.0
      },
      {
         "image_ids": 1147864,
         "scores": 26.0
      }
   ]
}
```

**Comment by gspinaci** [comment]
The check is be made **before** parsing the response. 

The system checks if:
* The body is a JsonObject
* If all the values related to first-level children keys are JSONArray
* If the JSONArrays length is equal

**Comment by lklic** [comment]
Great!!!

Is this check run on every request? If so, there are cases where we are firing off many of these requests simultaneously with often a lot of data as a response. This may affect performance in those cases….

**Comment by gspinaci** [comment]
Yes, the check is performed on every request, but it does not impact the performance greatly. On the other hand, the transposition algorithm goes through every element and changes the body structure, which may impact the performance.

But, in most API calls, the performances are mostly affected by the unknown delays given by the nature of the request (i.e., API calls pass through the Internet).

In our case, both the check and the transposition logic are structured not to change the computational order of the algorithm.

We can always change the algorithm not to update the body structure but instead perform the parse with a different logic.
