### ISSUE TITLE
Make bds:minRelevance default value configurable  

### ISSUE THREAD

**Issue by paolobonora** [researchspace/researchspace#253]
Within the [DefaultResourceSelectorQuery()](https://github.com/researchspace/researchspace/blob/master/src/main/web/components/semantic/search/config/Defaults.ts#L210-L225) the bds:minRelevance is set to 0.5.
Unfortunately that value may not fit the use case: i.e. when resources have very long labels as identifiers.
Is it possible to have a parameter within a config file to set the default bds:minRelevance to a different value?

**Comment by aindlq** [comment]
You can override the default query in the template, e.g 

```
<semantic-search-query-builder resource-selector='{"query": "
    prefix bds: <http://www.bigdata.com/rdf/search#>
    SELECT DISTINCT ?suggestion ?label WHERE {
      ?label bds:search ?__token__ ;
      bds:relevance ?score ;
      bds:minRelevance "0.1" ;
      bds:matchAllTerms "true"  .

      ?suggestion rdfs:label ?label .
      FILTER(EXISTS {
        { FILTER(?__relationPattern__) }
      })
    } ORDER BY DESC(?score)  LIMIT 30

"}'></semantic-search-query-builder>
```

**Comment by paolobonora** [comment]
Thanks @aindlq the suggestion works fine, we only had to specify also the "suggestionTupleTemplate" to make the dropdown show the options labels properly.
