### ISSUE TITLE
Possible missing pages and components

### ISSUE THREAD

**Issue by SamChaps** [researchspace/researchspace#26]
While migrating my app from the metaphactory platform 3.1.0 (trial license) to researchspace 3.2.1, there are several pages and react components that seems to be missing. I am wondering if it is the desired behavior since running the simple application from the researchspace/docker-compose/simple/ still illustrates the missing pages.

Here is a small list of the pages I am referring : 
- http://www.metaphacts.com/resource/admin/GraphScope.html
- http://help.metaphacts.com/resource/GraphScope.html
- http://www.metaphacts.com/resource/admin/QueryService.html
- http://help.metaphacts.com/resource/QueryAsAService.html

Here is a small list of the components I am referring : 
- mp-admin-query-api-manager
- graphscope-manager

Note: The help pages are referred in the researchspace simple app but they redirect to missing entities since the pages themselves are missing. As for the components, they are part of the admin pages that are missing too.

**Comment by aindlq** [comment]
Hi @SamChaps, as far as I understand you had trial license of "metaphactory platform", which is a commercial product from metaphacts. So I think all these missing pages and components are coming from metaphactory. They are not part of ResearchSpace platform.

**Comment by SamChaps** [comment]
Thanks for replying @aindlq, but I am wondering why is the Researchspace platform still referring to the mentionned pages? As far as I understand, the Researchspace platform does have the metaphactory core and its pages. Only, it seems that some are there and some are not. I am just trying to demystify why some pages are there and some not.
