### ISSUE TITLE
use Knowledge Patterns to list field values (was <mp-field-visualization> component)

### ISSUE THREAD

**Issue by vronk** [researchspace/researchspace#266]
After updating our RS-instances to the latest version, our template pages seem to choke on the component `<mp-field-visualization>`.
The pages keep on spinning the please-wait wheel, without any errors in the console.
(Except for a warning
`The "uri" property of "ResourceLinkComponent" is deprecated, please use the "iri" property instead [ResourceLinkComponent.ts:129:14](webpack:///src/main/web/api/navigation/components/ResourceLinkComponent.ts)` 
which I deem irrelevant in this regard.
)

What we want and need is the rather trivial application of the SELECT patterns of the Knowledge Patterns to list values of properties of a given resource in a template page.

Until now, we've used extensively something along these lines:
```
<mp-field-visualization
                  subject='[[this]]'
                  fields='[[fieldDefinitions
                              CreatorOfWork="https://omnipot.acdh.oeaw.ac.at/fieldDefinition/createdAsWorkBy"
                              mentionedIn="https://omnipot.acdh.oeaw.ac.at/fieldDefinition/mentionedIn"
                               ]]'
             template='{{> Platform:FieldsVisualization subject="[[this]]" [[#if asserted]]guess="true"[[/if]]}}'
          ></mp-field-visualization>
```

There does not seem to be such a template `Platform:FieldsVisualization` anymore.
We tried to exchange for what seems to be the replacement: `rsp:ResourceFieldBasedVisualization`, however to no avail,

Also, looking into the RS-codebase and documentation we see the Knowledge Patterns as well as the `fieldDefinition` helper being used only in combination with `<semantic-form>`-component.

Thus we are wondering if  `<mp-field-visualization>` component is actually still on, or what is the current recommended method to list values relying on the Knoweldge Pattern definitions.
This probably has a trivial resolution, but we are somewhat at a loss here.

Any hints would be very much appreciated.

**Comment by lklic** [comment]
Hello,

I can confirm that we actively use the `<mp-field-visualization>` component without any issues. if you are missing the `FieldsVisualization` template you are probably migrating from an older version of ResearchSpace before refactoring (the one with the British Museum theme). If that is the case there are a number of dependencies from that theme that have changed and/or been removed. Can you confirm which version you are migrating from?

You can see how we are using this component with the current build of ResearchSpace[ here](https://github.com/ArtResearch/artresearch.net/search?q=mp-field-visualization).

**Comment by lklic** [comment]
closing this, feel free to reopen if it is still an issue
