### ISSUE TITLE
Frames label system update

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#281]
Adding a new frame, using the thinking frames tech, automatically rename frames after their IDs. For instance, they can have meaningless names such as `Frame 45`, and the navigation through them can be hard.

New frames should be named after other parameters, such as the template that is going to be rendered or other.

**Comment by gspinaci** [comment]
@giancrys84 Have you already tought about this issue?

**Comment by dianat** [comment]
Hi, can you try out the frame-label-patch branch? It is @giancrys84 cherry picked plus master.

**Comment by gspinaci** [comment]
Thanks a lot! this is exaclty what i imagined! Can this be merged into master?

**Comment by dianat** [comment]
done

**Comment by dianat** [comment]
merged in master!
