### ISSUE TITLE
custom SPARQL DELETE query triggering <mp-ldp-remove-from-container-action>

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#29]
We aim to customize the DELETE SPARQL query that users trigger by clicking on the `<mp-ldp-remove-from-container>` element.

The current use case is the following: 
1. The insert form, shown below, allows users to create a new LDP container. Each container may or may not contain a triple pointing to its parent, which is stored in another LDP container (in row: ` "insertPattern": "INSERT { $subject <http://www.w3.org/2004/02/skos/core#broader> $value } WHERE {}",`).
```
<semantic-form
      new-subject-template="http://www.metaphacts.com/fieldDefinitionCategory/{{label}}"
      post-action="reload"
      browser-persistence="false"
      form-id="category"
      fields='[
            {
              "id": "label",
              "label": "Label",
              "description": "The name of the category",
              "xsdDatatype": "xsd:string",
              "minOccurs": "1",
              "maxOccurs": "unbound",
              "selectPattern": "SELECT $value WHERE { $subject rdfs:label $value }",
              "insertPattern": "INSERT { $subject rdfs:label $value } WHERE {}",
              "deletePattern": "DELETE { $subject rdfs:label $value } WHERE {}"
            },
            {
              "id": "parent",
              "label": "Parent Category",
              "description": "This will become the parent category",
              "xsdDatatype": "xsd:anyURI",
              "minOccurs": "0",
              "maxOccurs": "1",
              "selectPattern": "SELECT $subject WHERE { $subject <http://www.w3.org/2004/02/skos/core#inScheme> <http://www.metaphacts.com/ontologies/platform/FieldCategories> }",
              "insertPattern": "INSERT { $subject <http://www.w3.org/2004/02/skos/core#broader> $value } WHERE {}",
              "deletePattern": "DELETE { $category <http://www.w3.org/2004/02/skos/core#broader> $subject } WHERE { ?category <http://www.w3.org/2004/02/skos/core#broader> ?subject}",
              "treePatterns": {
                "type": "simple",
                "schemePattern": "?item <http://www.w3.org/2004/02/skos/core#inScheme> <http://www.metaphacts.com/ontologies/platform/FieldCategories>"
              }
            },                
            {
              "id": "type",
              "label": "Type",
              "description": "The type of the created instance",
              "xsdDatatype": "xsd:anyURI",
              "selectPattern": "SELECT $value WHERE { $subject a $value }",
              "insertPattern": "INSERT { $subject <http://www.w3.org/2004/02/skos/core#inScheme> $value } WHERE {}",
              "deletePattern": "DELETE { $subject <http://www.w3.org/2004/02/skos/core#inScheme> $value } WHERE {}"
            }
          ]'
      >
      <h3>Create a new Category</h3>
      <bs-panel>
        <semantic-form-recover-notification></semantic-form-recover-notification>
        <semantic-form-text-input for="label"></semantic-form-text-input>
        <semantic-form-tree-picker-input for="parent"></semantic-form-tree-picker-input>
        <semantic-form-hidden-input for="type" default-value="http://www.metaphacts.com/ontologies/platform/FieldCategories"></semantic-form-hidden-input>
        <semantic-form-errors></semantic-form-errors>

        <button name="submit" class="btn btn-default">Save</button>
        <button name="reset" class="btn btn-default">Reset</button>
      </bs-panel>
    </semantic-form>
```
2. The results are visualized within the <semantic-tree> component:
```
    <h3>List of Categories</h3>
    <semantic-tree
      query="
        PREFIX : <http://help.metaphacts.com/resource/>
        SELECT ?node ?parent WHERE {
          ?node <http://www.w3.org/2004/02/skos/core#inScheme> <http://www.metaphacts.com/ontologies/platform/FieldCategories> .
          optional { ?node <http://www.w3.org/2004/02/skos/core#broader> ?parent }

        }"
      tuple-template='{{> node}}'
      no-result-template='{{> empty-tree}}'
    >
      <template id='node'>
        <div><semantic-link uri="{{node.value}}"></semantic-link> {{> actions}}</div>
      </template> 

      <template id='empty-tree'>
        <div><strong>No categories found</strong></div>
      </template>

      <template id="actions">
        <span>
          <!-- Modal dialog -->
          <mp-overlay-dialog title="Are you sure?">

            <mp-overlay-dialog-trigger>
              <button class="btn btn-xs btn-danger" style="margin-right:8px;"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
            </mp-overlay-dialog-trigger>

            <mp-overlay-dialog-content>
                {{node.value}}/container
              <p><strong>You will not be able to recover this category</strong> (and all of its children) again!</p>
              <mp-ldp-remove-from-container-action iri="{{node.value}}/container" container="http://www.metaphacts.com/fieldDefinitionCategory/">
                <button class="btn btn-xs btn-danger" style="margin-right:8px;">Yes, Delete it!</button>
              </mp-ldp-remove-from-container-action>   

            </mp-overlay-dialog-content>

          </mp-overlay-dialog>
                       
        </span>
      </template>
    </semantic-tree>
```
3. For each element displayed in the tree, we have a `<mp-ldp-remove-from-container-action>`. Clicking this button it removes the LDP container.

4. If we have the following situation:
<img width="354" alt="Screenshot 2019-11-19 at 10 42 28" src="https://user-images.githubusercontent.com/8267319/69135365-4faa2680-0ab9-11ea-90c9-a815d9121bd5.png">
Which is the result of this query: 
<img width="1620" alt="Screenshot 2019-11-19 at 10 44 01" src="https://user-images.githubusercontent.com/8267319/69135515-83854c00-0ab9-11ea-97d8-dd60b512149a.png">
If a user deletes the child element, the result is the following: 
<img width="1573" alt="Screenshot 2019-11-19 at 10 46 08" src="https://user-images.githubusercontent.com/8267319/69135707-d7903080-0ab9-11ea-9cea-6632f12c62b0.png">
<img width="1620" alt="Screenshot 2019-11-19 at 10 45 53" src="https://user-images.githubusercontent.com/8267319/69135716-d959f400-0ab9-11ea-8919-1233aff39954.png">

The `semantic-tree` shows nodes and parents, based on the triple stored in the child container.
But if we delete a parent, we **have no chance** to remove also all the triples having as object the selected element (stored in another LDP container).

So, the questions are:
* **Is there any way to customize the delete query for an LDP container?**
* **If this is possible, can we inject the custom query as an attribute of the `<mp-ldp-remove-from-container>`?**
* **If this is not possible at all, are there any other possible workarounds?**

**Comment by aindlq** [comment]
As far as I know, by default `semantic-form` is working in ldp mode, that means that every entity is going to be stored in special LDP container - `http://www.metaphacts.com/ontologies/platform#formContainer`. Correct me if I'm wrong but I believe there is currently no way to customize the container.

so for it to work you need to use something like:
```
              <mp-ldp-remove-from-container-action iri="{{node.value}}/container" container="http://www.metaphacts.com/ontologies/platform#formContainer">
                <button class="btn btn-xs btn-danger" style="margin-right:8px;">Yes, Delete it!</button>
              </mp-ldp-remove-from-container-action>   
```

The downside is that there is no hierarchy of LDP containers for your categories, so there is no way to kind of in one go remove sub-hierarchy with one action.

**Comment by aindlq** [comment]
There is also `sparql` mode for `semantic-form`. It can be used to fully bypass LDP, but then you need to really careful with `deletePattern`. 

btw `deletePattern` for fields is not used in ldp mode.

**Comment by gspinaci** [comment]
Okay, thank you for your reply. We will work on a possible solution based on these two possible workarounds. 

We'll get in touch.

**Comment by lklic** [comment]
We will use the entity manager PR #184 as a solution for this.
