### ISSUE TITLE
Template can't be found for homepage

### ISSUE THREAD

**Issue by coy123** [researchspace/researchspace#3]
I am not sure how the templates are supposed to work but I can't get the researchspace working correctly and display the homepage after login. Here is what is displayed:

`It seems that the current resource "http://help.metaphacts.com/resource/Start" does not identify any application or template page as well as none of the applicable template pages is instantiated.`

**Comment by mike-kelly** [comment]
Please try the latest version. The admin templates are also now included, so the home page can be configured in the backend, under global configuration.

**Comment by mvb-iti** [comment]
`metaphactory/data/templates` has to be created manually even after today's update

**Comment by mike-kelly** [comment]
The installation instructions in the README have been updated to include the creation of the templates folder.
