### ISSUE TITLE
Researchspace does not support Graphdb sparqlEndpoint

### ISSUE THREAD

**Issue by acdh-ch** [researchspace/researchspace#300]
The Graphdb provides endpoint that expect SPARQL query:

curl -Lv --header 'Accept: application/sparql-results+xml' --data "query=SELECT+*+{?s+?p+?o.}  LIMIT 1" --user username:password 'https://graphdb-host/repositories/dbname'

Researchspace expects endpoint that ends with sparql: 
https://graphdb-host/repositories/dbname/sparql

It seems that Researchspace does not support Graphdb that is SPARQL 1.1 compliant.

**Comment by dianat** [comment]
Hi there,

I've tested the following configuration in RS using master branch to connect to a graphdb endpoint.

Add configuration below via the Repositories section
<img width="1281" alt="Screenshot 2024-05-13 at 11 16 48" src="https://github.com/researchspace/researchspace/assets/3415847/940adfb7-d3df-4f53-ab9b-6804269a16e4">


@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix sail: <http://www.openrdf.org/config/sail#> .
@prefix sr: <http://www.openrdf.org/config/repository/sail#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix mph: <http://www.researchspace.org/resource/system/repository#> .
@prefix ephedra: <http://www.researchspace.org/resource/system/ephedra#> .
@prefix fedsail: <http://www.openrdf.org/config/sail/federation#> .
@prefix sparqlr: <http://www.openrdf.org/config/repository/sparql#> .

[] a rep:Repository;
  rep:repositoryID "graphdb";
  rdfs:label "SPARQL repository with basic authentication";
  rep:repositoryImpl [
      rep:repositoryType "researchspace:SPARQLBasicAuthRepository";
      sparqlr:query-endpoint <http://localhost:7200/repositories/demo>;
      sparqlr:update-endpoint <http://localhost:7200/repositories/demo/statements>;
      mph:quadMode false;
      mph:writable true;
      mph:username "john";
      mph:password "****"
    ] .

**Comment by acdh-ch** [comment]
Thank you, I can confirm that, with this config graphdb.ttl,  RS can read/write to Graphdb.
But how to introduce sparqlr:query-endpoint and sparqlr:update-endpoint as ENV variables.
There is only one ENV variable related to sparqlEndpoint: "-Dconfig.environment.sparqlEndpoint" and for the Graphdb two variables are required?
