### ISSUE TITLE
Error when uploading `knowledgePatternsContainer.trig`

### ISSUE THREAD

**Issue by giobber** [researchspace/researchspace#339]
### Context
I'm trying to install the latest version of researchspace with docker compose
I've used the `docker-compose.yaml` inside the [linked repository](https://github.com/researchspace/researchspace-docker-compose) using the basic variant
I've incremented the Memory parameters in .env as suggested in #289 after having similar problems on starting the containers
```
RESEARCHSPACE_MEMORY=4g
BLAZEGRAPH_MEMORY=4g
```

### The problem
As stated in the project's README ([link](https://github.com/researchspace/researchspace?tab=readme-ov-file#setup-with-docker)) I've tried to upload the two .trig file found in [this repository](https://github.com/researchspace/researchspace-instance-configurations)
[ontologyContainer.trig](https://github.com/researchspace/researchspace-instance-configurations/blob/master/generic/ontologies_and_knowledge_patterns/ontologyContainer.trig) is uploaded without problems

[knowledgePatternsContainer.trig](https://github.com/researchspace/researchspace-instance-configurations/blob/master/generic/ontologies_and_knowledge_patterns/knowledgePatternsContainer.trig) **FAILED** with a generic error

Also I can't create entity or authorities, I don't know if it's related to this issue or is something else, in case I'll make another issue with all info and screenshots

Here the last lines of the logs:
```
researchspace-1  | *************************************************************************************
researchspace-1  | * Main platform servlet context initialized. Press CTRL+C to terminate the process. *
researchspace-1  | *************************************************************************************
researchspace-1  | 
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:265) - Initializing HTTP Sparql Repository with URL: http://blazegraph:8080/blazegraph/sparql.
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:323) - Trying to initialize repository with id "default"
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:349) - Repository with id "default" successfully initialized
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:323) - Trying to initialize repository with id "tests"
researchspace-1  | 2024-06-16 00:45:07 WARN  [main] (DirectoryLockManager.java:165) - Removing invalid lock 1@25928d576cc5
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:349) - Repository with id "tests" successfully initialized
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:323) - Trying to initialize repository with id "assets"
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:349) - Repository with id "assets" successfully initialized
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:323) - Trying to initialize repository with id "osm-nominatim-search"
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:349) - Repository with id "osm-nominatim-search" successfully initialized
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:323) - Trying to initialize repository with id "ephedra"
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:349) - Repository with id "ephedra" successfully initialized
researchspace-1  | 2024-06-16 00:45:07 INFO  [main] (RepositoryManager.java:298) - Testing connection for repository "default".
researchspace-1  | 2024-06-16 00:45:08 WARN  [main] (RepositoryManager.java:305) - Connection to repository "default" has been established successfully. However, repository seems to be empty.
researchspace-1  | 2024-06-16 00:45:08 INFO  [main] (RepositoryManager.java:298) - Testing connection for repository "assets".
researchspace-1  | 2024-06-16 00:45:08 WARN  [main] (RepositoryManager.java:305) - Connection to repository "assets" has been established successfully. However, repository seems to be empty.
researchspace-1  | 2024-06-16 00:45:08 INFO  [main] (LDPAssetsLoader.java:123) - Loading LDP assets...
researchspace-1  | 2024-06-16 00:45:08 INFO  [main] (LDPAssetsLoader.java:171) - Loading 56 LDP assets into the "assets" repository
researchspace-1  | 2024-06-16 00:45:08 INFO  [main] (LDPAssetsLoader.java:200) - Read 1 assets. Loading into the repository...
researchspace-1  | 2024-06-16 00:45:09 INFO  [main] (LDPAssetsLoader.java:221) - Loading finished.
researchspace-1  | 2024-06-16 00:45:09 INFO  [main] (LDPAssetsLoader.java:161) - All LDP assets loading finished
researchspace-1  | 2024-06-16 00:45:09 INFO  [main] (MDCFilter.java:99) - Init MDC Filter.
researchspace-1  | 2024-06-16 00:45:10 INFO  [main] (PlatformPluginManager.java:143) - Detected the following REST Extensions: []
researchspace-1  | 2024-06-16 00:45:10 INFO  [main] (RestApplicationExtension.java:49) - Trying to register the following RestExtensions: []
researchspace-1  | 2024-06-16 00:45:10.298:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@23f5b5dc{/,file:///tmp/jetty/jetty-0_0_0_0-8080-ROOT_war-_-any-13816220321964646711.dir/webapp/,AVAILABLE}{/var/lib/jetty/webapps/ROOT.war}
researchspace-1  | 2024-06-16 00:45:10.315:INFO:oejs.AbstractConnector:main: Started ServerConnector@368ff8be{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
researchspace-1  | 2024-06-16 00:45:10.316:INFO:oejs.Server:main: Started @9270ms
researchspace-1  | 2024-06-16 00:47:43 ERROR [qtp1846406218-28] (ContainerEndpoint.java:459) - Something went wrong. Exception while import LDP resource. Resource: . Error: error executing transaction
```

![ResearchSpace-Error1](https://github.com/researchspace/researchspace/assets/14294684/924ba2cf-9313-4ca7-b9c1-4795ee015f49)

**Comment by dianat** [comment]
Hi @giobber,

Do you get any errors from docker? You can try something like docker logs [name_of_the_researchspace_container}

Also in your .env you can edit the following:
RESEARCHSPACE_MEMORY=2g
BLAZEGRAPH_MEMORY=2g

RESEARCHSPACE_JAVA_OPTS=-Xms1450m -Xmx1450m -Dlog4j2.formatMsgNoLookups=true
BLAZEGRAPH_JAVA_OPTS=-Xms1450m -Xmx1450m -Dlog4j2.formatMsgNoLookups=true

d.

**Comment by giobber** [comment]
The logs I shared in the first message where the last lines from `docker compose logs`

As I write I've already increment RESEARCHSPACE_MEMORY and BLAZEGRAPH_MEMORY, I'll try with 2g instead of 4g

I'll try the other java options you have suggested as soon as possible

Thank you for the support

**Comment by giobber** [comment]
For some reason, I need to use `sudo` when launching `fix-folder-permissions.sh`, although is not requested in the basic [README.md](https://github.com/researchspace/researchspace-docker-compose/blob/master/basic/README.md) 

I think the README assumes that command are launched as root
(but I'm on archlinux so maybe I'm the problem :D)

---

I confirm that, with the new options you give me it works.
`knowledgePatternsContainer.trig` is uploaded without errors (althought it requires a lot of time to complete)

**Comment by giobber** [comment]
I also confirm that "Entity Editor" and "Authority and entity configuration" are present in settings

I'll share the final `.env` I used for sake of completeness
```
# (required) your project name, to have nice container names in the docker-compose setup.
# see https://docs.docker.com/compose/reference/envvars/#compose_project_name
COMPOSE_PROJECT_NAME=permea

# (required) memory limits for docker containers

# Total amount of memory available for containers
RESEARCHSPACE_MEMORY=4g
BLAZEGRAPH_MEMORY=4g
DIGILIB_MEMORY=500m

# (optional) additional ReseearchSpace runtime options.
# By default increases jetty upload limit to ~100mb
RESEARCHSPACE_OPTS=-Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000

# (optional) additional JVM opts for various applications
# WARNING! Don't set Xmx here, use memory variables above. We use -XX:+UseContainerSupport, see https://merikan.com/2019/04/jvm-in-a-container/ for more details about memory management of Java apps inside docker.
RESEARCHSPACE_JAVA_OPTS=
BLAZEGRAPH_JAVA_OPTS=
DIGILIB_JAVA_OPTS=

# docker images
RESEARCHSPACE_IMAGE=researchspace/platform-ci:latest
BLAZEGRAPH_IMAGE=researchspace/blazegraph:latest
DIGILIB_IMAGE=robcast/digilib:latest

RESEARCHSPACE_JAVA_OPTS=-Xms1450m -Xmx1450m -Dlog4j2.formatMsgNoLookups=true
BLAZEGRAPH_JAVA_OPTS=-Xms1450m -Xmx1450m -Dlog4j2.formatMsgNoLookups=true
```

**Comment by giobber** [comment]
One last thing

Before launching the final configuration I tried without the two `_JAVA_OPTS` variables. Obviously the upload failed as the first time, but I noticed that the error was caused not from researchspace container but from the blazegraph one which at some point during the upload crashes and restart saying `blazegraph-1 exited with code 0`

**Comment by dianat** [comment]
Hi @giobber thank you for detailing your experience, we are currently preparing a version (to be made available in September 2024) that will do all of this work of generating or loading the right KPs automatically as they will be part of the codebase explicitly or generated when starting up for the first time. We will announce then some dates for "How to sessions" for people interested in using the new version. And hopefully we will update some of the existing documentation.
