### ISSUE TITLE
Pass API-KEY from configuration file 

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#35]
I would call these new properties `provider` and `providerOptions`, BaseMap style can go into `providerOptions`.

> In addition, we also need to pass API-KEYs. Is there any way to do that in a secure way?

Ideally one should be able to use builtin proxy for that, but currently it doesn't support addition of query parameters to proxied request. It shouldn't be to hard to add it, have a look into `MProxyServlet.java` and `ProxyConfigs.java`. You can add `tokenQueryName`  and `tokenQueryValue` parameters to `ProxyConfigs` and then modify request in `MProxyServlet`. If you decided to have a look, please do it as a separate PR.

Meanwhile you can also rewrite requests in nginx.

_Originally posted by @aindlq in https://github.com/researchspace/researchspace/issues/32#issuecomment-559413737_

**Comment by lklic** [comment]
I haven't had an in-depth look at the the proxy handler, but would it make more sense to pass in the API key through the Docker-compose file as an environment variable?

**Comment by aindlq** [comment]
That is how I see it. Lets say you have map component:
```
<semantic-map provider='mabpox' provider-options='{"endpoint": "http://localhost:10214/proxy/mapbox"}'></semantic-map>
```

Then in the proxy.conf file:
```
config.proxy.mapbox.targetUri=https://api.mapbox.com
config.proxy.mapbox.tokenQueryName=access_token
```

And then when starting you can provide the actual token:
```
-Dconfig.proxy.mapbox.tokenQueryValue=your_token
```
actually the whole proxy config can be provided through `-D` params.

Does it make sense or do you see it differently?
