### ISSUE TITLE
Don't automatically generate and upload KPs for ontologies.

### ISSUE THREAD

**Issue by aindlq** [researchspace/researchspace#350]
In the latest version `LDPAssetsLoader` tries to automatically generate and upload KPs for ontologies. 

I guess it should be put behind some config flag, otherwise it unexpectedly tries to write to a repo, even when assets loading is disabled.

**Comment by dianat** [comment]
Hi, we've added several repos that proxy to default. The key repositories that are being used for KPs and ontologies are system and ontologies. These are separate repositories from assets. The system KPs are essential for admin and user-orientated templates. The overall intention is to ensure a working setup for most of the components that make ResearchSpace from the first initialisation.

Is there a particular setup you've tested this with and it doesn't work for you. Can you share some details of that configuration so I can find an approach that considers better existing setups?

**Comment by aindlq** [comment]
Hi Diana. That is fine when you start a fully empty instance from scratch.

> several repos that proxy to default

That is the problem. Especially for people who are already using RS or are going to try it out on their own data. It can be quite unexpected to find your data repository populated with ontologies and hundreds of RS KPs, by updating to a new RS version.

I wonder how much the whole thing depends on the fact that these special repositories = default?
