### ISSUE TITLE
build-docker branches build automatically fail

### ISSUE THREAD

**Issue by gspinaci** [researchspace/researchspace#356]
The build job, after pushing on a build-docker branch, automatically fails. It is required to update the specific tag for the researchspace/platform-ci docker image.

See this log: https://github.com/researchspace/researchspace/actions/runs/10813708470/job/29998365775

**Comment by dianat** [comment]
Hi @gspinaci can you try to modify the .github/workflow/main.yml and change to v4. 
Thank you for pointing this out. I did a test on a build-docker/oxigraph-fix branch with the change and it worked.
<img width="916" alt="Screenshot 2024-09-11 at 23 01 46" src="https://github.com/user-attachments/assets/ce5e3d0a-a03d-4989-85ea-6e22b5dffa96">

**Comment by gspinaci** [comment]
Thank you @dianat! It works!

**Comment by gspinaci** [comment]
If it hasn't been updated in the main branch, I will create a new PR and add it there.
