### ISSUE TITLE
cidoc-crm from version 6.2.1 to 7.1.3

### ISSUE THREAD

**Issue by leonardol** [researchspace/researchspace#357]
Hi all,

Is it possible to change the version of the cidoc-crm from 6.2.1 to 7.1.3 in Researchspace? Can the two versions coexist in Researchspace?

**Comment by dianat** [comment]
Hi @leonardol you can delete the old 6.2.1 and upload the newer version. Please look at the existing cidoc crm trig file as an example of how the file you are uploading should be structured (a trig file where the graph is titled http://www.cidoc-crm.org/cidoc-crm/context). System templates and system knowledge patterns were created based on 7.1.3. It doesn't make sense from a data perspective to have co-existing versions, so one should make a choice between versions.

**Comment by leonardol** [comment]
Hi @dianat, I have modified the file [CIDOC_CRM_v7.1.3.trig](https://gitlab.isl.ics.forth.gr/cidoc-crm/cidoc_crm_rdf/-/blob/master/7.1.3/other_encodings/CIDOC_CRM_v7.1.3.trig) according to your suggestion. The result is the following file: [CIDOC_CRM_v7.1.3.zip](https://github.com/user-attachments/files/17129729/CIDOC_CRM_v7.1.3.zip). I have uploaded it, and everything seems to be working well.

**Comment by leonardol** [comment]
To be more specific, I restarted the application using the Gradle task `runAll`.
So, I solved the issue by replacing the codebase file `researchspace/src/main/resources/org/researchspace/apps/default/ldp/ontologies/cidoc_6.2.1.trig` with the file `researchspace/src/main/resources/org/researchspace/apps/default/ldp/ontologies/cidoc_7.1.3.trig` (with the same content of the file CIDOC_CRM_v7.1.3.trig mentioned above) without deleting the old 6.2.1 and uploading the newer version via the administrator panel.
