### ISSUE TITLE
Strange behaviour of dropdowns in nav header

### ISSUE THREAD

**Issue by aindlq** [researchspace/researchspace#362]
With the latest master. When I hover the mouse over a header item that is a dropdown, it opens and I can see nested options. For example moving the mouse over user name I can see user profile and logout options.

But if I try to move the mouse over profile or logout options, dropdown immediately closes. The only way to click an option is to first click on the dropdown, so in this case user name. Then it will stay open and I can click on profile or logout. 

This is very annoying.

I believe the reason is that  `.dropdown-menu` has a tiny top margin, so when I move the mouse from dropdown toggle to dropdown menu it gets into that margin and it triggers dropdown close.

**Comment by giancrys84** [comment]
hi! 
Thanks for reporting this.
It's now fixed in [PR#363](https://github.com/researchspace/researchspace/pull/363)
