### ISSUE TITLE
Node compatibility: use 7 or 8, not 9

### ISSUE THREAD

**Issue by maximbashevoy** [researchspace/researchspace#4]
The platform won't build on node 9 because of `node-sass` compatibility issue. Exact error:
```
project/webpack/node_modules/node-sass: Command failed
```
Use `brew install node@8` on a Mac.

**Comment by mike-kelly** [comment]
I have specified Node 6, 7 or 8 in the README until this is fixed.

**Comment by suchmaske** [comment]
In my case I needed to rebuild node-sass in `project/webpack` and everything worked after that (I am using node 10 on Arch Linux).

`yarn add --force node-sass` re-downloads and rebuilds that package.

**Comment by aindlq** [comment]
now ResearchSpace can be build with any LTS version of Node - 8, 10 or 12.
