### ISSUE TITLE
defining user role that allows only to read and create data

### ISSUE THREAD

**Issue by fdiehr** [researchspace/researchspace#44]
hey, 
I like to create user accounts, that have the permission to view pages and to create data (write in the triple store via using the templates). Nothing else.
I created a new user with the roles "guest" and "root", but that did not work. 
1) what permissions are needed to let users create data?
2a) how can I add the permission to an existing role? (shiro.ini I guess?)
or
2b) how can I define new roles?

**Comment by aindlq** [comment]
What do you mean by "but that did not work"?

1. If you are creating data with `semantic-form` then you need to have `forms:ldp:*` permission. Permission is defined here - https://github.com/researchspace/researchspace/blob/master/metaphacts-platform/core/src/main/java/com/metaphacts/security/Permissions.java#L334

2a) Yes you need to modify shiro.ini file, just add permission that you need to corresponding role. Here is default shiro.ini file - https://github.com/researchspace/researchspace/blob/master/metaphacts-platform/app/config/shiro.ini . As you can see `admin` role has `forms:ldp:*` permission, but `guest` role doesn't have it.
2b) Add new role in the `[roles]` section of shiro.ini file. See https://shiro.apache.org/configuration.html#Configuration-%5Croles%5C .

**Comment by fdiehr** [comment]
ah super, thank you for the quick response! that's exactly what I needed to know.

I added a new role "editor" to the shiro.ini (having the permissions that "guest" has, plus `forms:ldp*`. but the role is not shown in the dropdown after building the platform.
(totally "fresh" build, used `docker-down --volumes` to get rid of all former states, and `docker-build --no-cache` for building the platform.) 
what could be the problem?

(regarding "but that did not work": it couldn't have worked in the first place, for the roles do not have the permissions, I needed. Creating the user with the roles did work though, I didn't put it right above, sorry.)

**Comment by aindlq** [comment]
hm hard to answer without more details about your environment.

How are you running ResearchSpace? Are you using docker-compose with existing image or do you have your own way of building it from sources?

**Comment by fdiehr** [comment]
i run RS (version 3.2.1) with an app i have created. (running inside `researchspace/apps/<my_app>`). I use git for version control of the apps's development ([here](https://github.com/fdiehr/entermuseum4punkt0)). (i checked if the changes I made in my app are also run on the server, and they do.)
RS image and the app live on a server which is build using an ansible playbook. have a look at the my test instance, if you want: [http://researchspace.curving.space/] (http://researchspace.curving.space/)

do you need anymore information?

**Comment by aindlq** [comment]
I believe that currently it is not using shiro.ini from your app. See https://researchspace.curving.space/resource/Help:Storage#storage-and-apps

```
Local user credentials and/or role definitions (config/shiro.ini).
Please note that this requires to instruct the security module to read the shiro file explicitly from the storage and not from the default file system. This can be done by setting property securityConfigStorageId:

-Dconfig.environment.securityConfigStorageId=[storage-id]
```

In your case `-Dconfig.environment.securityConfigStorageId=entermuseum4punkt0`.

**Comment by aindlq** [comment]
jfyi, I can see that you have many `semantic-link` with prefixed IRI, it actually expects full IRI. That is why when you navigate to some page and click "edit" you don't see any template.

So instead of `<semantic-link title="m4p0:DigitalApp" uri=":DigitalApp" target=_blank>Digitale Anwendung</semantic-link>` please use
 `<semantic-link title="m4p0:DigitalApp" iri="https://www.museum4punkt0.de/catalogue/ontology/DigitalApp" target=_blank>Digitale Anwendung</semantic-link>`
or
`<semantic-link title="m4p0:DigitalApp" iri='[[resolvePrefix ":DigitalApp"]]' target=_blank>Digitale Anwendung</semantic-link>`

And also I think `uri` parameter is deprecated, please use `iri` instead.

**Comment by fdiehr** [comment]
hey, 
thank you for the hint with uri/iri and also the `semantic-link`.
using `iri='[[resolvePrefix ":MyTemplate"]]` worked everywhere except in the header.hbs. here I had to use the full iri.

**Comment by fdiehr** [comment]
concerning the shiro.ini:
we set the security property as you indicated it and it worked: the system uses the shiro.ini from my app.
but with this comes a quite inconvenient way of user administration: as we thought in advance, using the shiro.ini form the app, it is not possible now to create user via the browser interface. also creating new users via shiro.ini is not really possible, because you have to have an hash for any user. 
of course there is a workaround: at first in *foresight* one could predict all possible users of the system or create some genric users via the interface using the shiro.ini from the source app. than deploying the system with the security property using shiro.ini from app. than, creating the role and edit the users (which have an hash now) with the new role.
this is maybe possible for a first roll-out of our app and RS system, but it will not working well with a running, productive system. 
my question is now: is there another way to workaround this issue? do we miss something?

**Comment by aindlq** [comment]
Hm, to be honest I didn't tried but from the source code I don't see why it shouldn't work. Does it throws any exception?

Make sure that folder and file have correct permissions on the filesystem and can be edited by user with id 100,  group id 101. This is uid/guid used by jetty user inside platform docker container.

Also it is possible to configure integration with LDAP instead of simple file based user management.

**Comment by fdiehr** [comment]
> Does it throws any exception?

no, it's about the usage, not an error/bug of the system. 

> Make sure that folder and file have correct permissions on the filesystem and can be edited by user with id 100, group id 101. This is uid/guid used by jetty user inside platform docker container.

that's right and the problem description doesn't actually hint on a problem in this regards. there is no problem with permissions. when using shiro.ini from my app, it is not possible to create users via the interface. this is the error message:
`com.metaphacts.services.storage.api.StorageException: Cannot write to read-only storage`

I understand the message that way: when shiro.ini is used from my app, changes on shiro.ini in runtime storage is not possible. 
that's why we need a solution for creating users in the interface AND using configured user roles as defined in shiro.ini of my app.

> Also it is possible to configure integration with LDAP instead of simple file based user management.

LDAP is not feasible for our project at all. (even if: how would the app configure roles/permissions in that LDAP?)

**Comment by aindlq** [comment]
ah, I see. By default app is mounted in readonly mode (as shown here https://researchspace.curving.space/resource/Admin:Apps), you can change that.
See https://researchspace.curving.space/resource/Help:Storage#storage-and-apps for more details about apps and storages: 

```
* Every app has exactly one associated storage.
* A storage is associated to an app by its ID, i.e. the plugin.id must be equal to the storage ID.
* If no storage is defined for an app, a default nonVersionedFile storage is defined. The root of the storage folder will be set to the root of the app folder.
```

So I believe you need to add something like this to start options: `-Dconfig.storage.entermuseum4punkt0.type=nonVersionedFile -Dconfig.storage.entermuseum4punkt0.mutable=true -Dconfig.storage.entermuseum4punkt0.root=/apps/entermuseum4punkt0`

Make sure that you specify correct location in the `-Dconfig.storage.entermuseum4punkt0.root`.

Another option is to keep your current app as is but define new mutable storage and use it for shiro file.
