### ISSUE TITLE
"ERROR WHILE SAVING THE PAGE" on ResearchSpace 3.3.0 docker-compose image

### ISSUE THREAD

**Issue by liladude** [researchspace/researchspace#49]
Hello,
today I created a new docker-composer local instance, but whenever I try to save a page, I get an error that says "ERROR WHILE SAVING THE PAGE". 
I have checked inside the docker image shell and I suspect there could be some kind of ownership errors. Not even the logs are updated.
Did I miss something?
Best regards,
Lila

**Comment by aindlq** [comment]
Are you trying to save a new page or modifying an existing one?

In the top of the page editor there is section like this:
![image](https://user-images.githubusercontent.com/2255044/76295499-65886500-62bd-11ea-9481-31b97b66f6af.png)

What values for "App overrides" and "Target App" do you have for the page that you are trying to save?

**Comment by liladude** [comment]
Thank you for your answer. 
If I try to modify the page I have `App overrides: 
example-app
Target App: runtime` Everything else is read only
If I try to create a new page I see again `Target App: runtime` and everithing else is locked.
![New_page](https://user-images.githubusercontent.com/5690679/76298159-556e8680-62b9-11ea-8e26-408917828967.png)
I attached a screenshot, I hope this helps!

**Comment by aindlq** [comment]
1. What OS are you using?
2. Did you change anything in docker-compose.yml or .env files?

**Comment by liladude** [comment]
Os is Debian 9, I had to change the port (8889:8080) on docker-compose.yml

**Comment by aindlq** [comment]
That is definitely something environment specific. I've tried on clean Ubuntu VM and it seems to be working fine.

Try to look into permissions for `/runtime-data` inside researchspace container, here is what I have:
```
/runtime-data/data $ ls -alh
total 16
drwxrwsr-x    4 jetty    root        4.0K Mar 10 14:41 .
drwxrwsr-x    4 jetty    root        4.0K Mar 10 14:40 ..
drwxrwsr-x    3 jetty    root        4.0K Mar 10 14:40 repositories
drwxrwsr-x    2 jetty    root        4.0K Mar 10 14:41 templates
/runtime-data/data $
```
Can you create there any folder/file if you get into container with user `-u jetty`?

Also you can try to mount empty folder on the host machine into `/runtime-data`, my feeling is that something is wrong with the volume.

**Comment by liladude** [comment]
I have the very same permissions, I will see if I can create the files and report back!

**Comment by liladude** [comment]
I went ahead and tested from the machine itself as localhost:8889, and it seems to work with no problem. Looks like I have troubles around my domain redirect that let me access the machine from ourside my local network.

**Comment by aindlq** [comment]
OK, great that you solved it!

>  I was wondering why I can't see the logs updated under /var/lib/jetty/webapps/etc/log4j2.xml
That is configuration file, look into `docker logs`

Also sometimes when there are no back-end logs it worth to look into browser dev tools to see if there are any errors there or if there are failed requests in the network tab.

**Comment by liladude** [comment]
It was a misconfiguration of the virtual host, somehow, when accessed on the port 80. SSL and port 443 worked fine so I'm all set!
