### ISSUE TITLE
How to deploy and make accessible from remote machine

### ISSUE THREAD

**Issue by zarquon42b** [researchspace/researchspace#5]
Hi,
I am trying to install it on a local server and grant my colleagues access. While I can access researchspace via localhost, when accessing it from another computer (via IP), I get a somewhat weird looking login page that takes me to a blank site. I guess there is some config needed that points to the correct resources from a remote machine. 
Is there an easy way to fix this?
All the best
Stefan

**Comment by zarquon42b** [comment]
Update:
it seems that the path to local resources is still set to localhost for remote machines - which obviously does not work (see image)
![selection_202](https://user-images.githubusercontent.com/1515863/40052572-8e70b688-583e-11e8-8c83-dfce2382cb91.png)

**Comment by dpancic** [comment]
I had the same problem and solved it with Apache reverse proxy.

```
    ProxyPass                  /assets/          http://localhost:3000/assets/ 
    ProxyPassReverse    /assets/           http://localhost:3000/assets/

    ProxyPass        /                              http://localhost:10214/ 
    ProxyPassReverse /                         http://localhost:10214/
```

**Comment by zarquon42b** [comment]
Thanks a lot @dpancic ! 
I added it to a virtualhost config (I am by no means a qualified web admin), however, while I can access the site now without specifying the 10214 port, the localhost:3000/asset error still persists. 
It would be really kind of you if you could point me in the right direction.

**Comment by zarquon42b** [comment]
I forgot to mention that the reverse proxy works well, however, the url pointing to the data still is set to localhost:3000, which obviously does not get processed correctly on a remote machine.

**Comment by dpancic** [comment]
Try to replace all occurrences of http://localhost:3000 with https://your_domain.com in:
https://github.com/researchspace/researchspace/search?utf8=%E2%9C%93&q=localhost%3A3000&type=

**Comment by zarquon42b** [comment]
Thanks! I am actually trying that right now. I was hoping for a less dirty hack ;)

**Comment by mike-kelly** [comment]
Sounds like you are running in development mode. Try `build.sh -DBUILD_ENV=prod`
There is more info in `/metaphactory/README.md`

**Comment by zarquon42b** [comment]
@mike-kelly Unfortunately there is no file `/metaphactory/README.md` and using your command, the issue still persists:

```
Loading failed for the <script> with source “http://localhost:3000/assets/no_auth/dll.vendor.js”.
rsp:Search:12
Loading failed for the <script> with source “http://localhost:3000/assets/no_auth/dll.hot.js”.
rsp:Search:14
Loading failed for the <script> with source “http://localhost:3000/assets/api-commons-bundle.js”.
rsp:Search:17
Loading failed for the <script> with source “http://localhost:3000/assets/app-bundle.js”.
```

**Comment by mike-kelly** [comment]
Hi @zarquon42b Stefan,
Sorry, that README was removed because it needed to be updated, but we will add further documentation on this soon. For the moment the existing README just covers the setting up of the dev environment, which is why there is a service at localhost:3000 for hot reloading of code changes.
There are a few different options for packaging a production version, including building Docker images or a .war file. I'll update this issue when the documentation is in place.

**Comment by zarquon42b** [comment]
Hi @mike-kelly ,
thank you for your response. I am looking forward to the final production version to allow my colleagues to evaluate researchspace in our local network for using it in a research project.

**Comment by aindlq** [comment]
https://github.com/researchspace/researchspace#setup-with-docker
