### ISSUE TITLE
GIT storage as runtime storage not working

### ISSUE THREAD

**Issue by sennierer** [researchspace/researchspace#50]
I am trying to get the GIT storage as runtime storage working. But whatever I try I get permission errors when saving e.g. a template.

`com.metaphacts.services.storage.api.StorageException: Failed to insert object content into Git object database`
`Caused by: java.io.IOException: Permission denied`
I am using the 3.3.0 docker image with docker-compose and was following the help doc on how to set that up.

Does anyone have an idea how to solve that?

**Comment by dpancic** [comment]
Please try with
 `chown -R 100:101 /git-runtime-data`

**Comment by sennierer** [comment]
yes, that was the problem Thanks very much!
