### ISSUE TITLE
Data for Triplestore

### ISSUE THREAD

**Issue by Knurg** [researchspace/researchspace#7]
I don't want to use blazegraph/docker and tried to get the software running. 
The sparql-connection seems to work, however I would need the example files in some more standard format like .nq - could you please provide these, so that the system can work with other triplestores? Did I miss them in this repo somewhere?

Thanks in advance!

**Comment by lklic** [comment]
You can configure external repositories by navigating to `/resource/Admin:Repositories`

There are pre-defined templates there that you can use for other graph databases, including stardog, although I am not sure if this has been tested recently. Your graph database should be configured to support quads (named graphs).
