### ISSUE TITLE
Is it AGPL or GPL?

### ISSUE THREAD

**Issue by adamretter** [researchspace/researchspace#71]
I am a little bit confused, your README.md file clearly states that ResearchSpace is AGPL, but the license headers of your source files clearly state that it is GPL.

I am wondering, which one is it?

**Comment by doldman** [comment]
Dear Adam,

The whole project is AGPL (README and LICENSE). There is compatible GPL
code within it but which is incorporated under the overall AGPL license.

Hope that helps.

Dominic

PS. It does look like Neptune has more stuff compared when we tested it. We
would be very interested to know the results of your tests.

**Comment by aindlq** [comment]
It is AGPLv3 or later as stated in README.md and LICENSE file. For historical reasons it contains files that have GPLv3 or later license, AGPLv3 subsumes GPLv3.
