### ISSUE TITLE
ability to pass in array into mp-field-visualization component

### ISSUE THREAD

**Issue by lklic** [researchspace/researchspace#76]
We make heavy use of the mp-field-visualization component to display our data and dynamically pull up fields related to the subject of an entity that we are exploring.

With the Pharos project, we have one canonical URI that describes a person, a work of art, an institution, etc which then has one or many owl:sameAs links to entities from partner project datasets, Wikidata, VIAF, ULAN, AAT, etc. Our goal is to be able to visualize all of this data together, traversing these sameAs links from different sources within the mp-field-visualization component. 

While we could build our field definitions with UNIONS to account for sameAs links, given the large number of fields it would be more efficient and manageable for our field definitions to be able to pass in an array of URI's into the mp-field-visualization rather than a single subject as a string:
https://github.com/researchspace/researchspace/blob/493aa66bdcb0263e66c88cc91928fc174aa55791/src/main/web/components/forms/FieldBasedVisualization.ts#L38

If there is more than one URI as the subject, each would get evaluated for each field definition, with results being grouped together under individual fields, rather than having repeating field labels for each subject in the array.

using the jsonArrayFromSelect Helper one could pass in an array of URI's with a simple query:
[[jsonArrayFromSelect "SELECT ?sameAsThis WHERE { [[this]] owl:sameAs ?sameAsThis}"]]

I have heard from other Cordh partners who would also be interested in this change.

Thanks!

**Comment by aindlq** [comment]
The component is extremely simple - https://github.com/researchspace/researchspace/blob/master/src/main/web/components/forms/FieldBasedVisualization.ts#L102. 

So it shouldn't be a problem to add this logic to it. PR is welcome.

**Comment by lklic** [comment]
Yep, we are already working on it!

We are thinking to add another (optional) variable to pass in, that accepts an array, as not to disrupt current functionality. Will create a PR soon....

**Comment by lklic** [comment]
This is brilliant, thanks!

I still have some more testing to do, will close once this is done.

Thanks again!
