### ISSUE TITLE
More than one triple store connection

### ISSUE THREAD

**Issue by Knurg** [researchspace/researchspace#8]
Is it possible to have more than one triple store connection on the backend to aggregate all the data sources I have?

Thanks in advance!

**Comment by suchmaske** [comment]
I think that is possible. I am currently also just trying out researchspace. While browsing the documentation in my local instance, I found a Java-Snippet that shows example code how to access a triple store. Unfortunately, I could not find this snippet in the official online-demo of researchspace.

Take a look [here](https://github.com/researchspace/researchspace/blob/master/researchspace/app/data/templates/http%253A%252F%252Fhelp.metaphacts.com%252Fresource%252FWorkingWithData.html)

**Comment by lklic** [comment]
Please see this issue: #7 

We should update the documentation to make this more clear.
