### ISSUE TITLE
platform build fails with new version of node from homebrew

### ISSUE THREAD

**Issue by lklic** [researchspace/researchspace#92]
I had to wipe my computer and am working from a fresh install of everything.

I installed the latest version of node with homebrew:
`brew install node`

The build failed with the latest version so to fix it I had to run:

`brew install node@12`
`brew unlink node`
`brew link node@12`

for the failed version `node --version` returned `v14.4.0`

For a fresh install would probably be best to just run `brew install node@12` until the issue is fixed.

**Comment by PaulWang1905** [comment]
Thanks for the tip.  I always build on virtual machine to be just in case.

**Comment by aindlq** [comment]
Thanks, I've update README as part of https://github.com/researchspace/researchspace/pull/93 change
