### ISSUE TITLE
defining user role that allows only to upload RDF files

### ISSUE THREAD

**Issue by sennierer** [researchspace/researchspace#97]
Hi,
I am trying to create a role that allows to upload RDF files, but not delete named graphs etc.

However, I am always getting a 403: Problem accessing /rdf-graph-store. Reason: Forbidden

I added the sparql:update permissions to a new role in shiro.ini, but I guess I also need to add a file upload permission?

**Comment by aindlq** [comment]
I think you need `sparql:graphstore:get`, you don't need`sparql:update`, it is for query execution through sparql endpoint. `rdf-graph-store` is dedicated endpoint - https://github.com/researchspace/researchspace/blob/490dad989b855c61f860eae8175e650f92c6d2fa/src/main/java/org/researchspace/rest/endpoint/RDFGraphStoreEndpoint.java#L126

jfyi, all permissions are listed here https://github.com/researchspace/researchspace/blob/490dad989b855c61f860eae8175e650f92c6d2fa/src/main/java/org/researchspace/security/Permissions.java#L220

**Comment by aindlq** [comment]
Oh, copy/pasted the wrong one. It is `sparql:graphstore:create`

**Comment by sennierer** [comment]
```sparql:graphstore:create``` was the correct one. Thanks very much!
